root = "."

tmp_dir = "tmp"

[build]
  # 1. Compilamos. Usamos -o para nombrar el output dentro de /tmp.
  # No incluyas .go en el nombre del output.
  cmd = "go build -gcflags='all=-N -l' -o ./tmp/main.exe ./cmd/api/main.go"
  
  # 2. En Windows, Air a veces necesita que bin apunte al ejecutable generado
  bin = "./tmp/main.exe"
  
  # 3. Ejecutamos mediante Delve. 
  # Importante: dlv debe ejecutar el .exe generado en el paso 1.
  full_bin = "./tmp/main.exe"

[misc]

  clean_on_exit = true